sudo: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"

cache: npm
notifications:
  email: false

script:
  - npm run lint
  - npm test
jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: skip
      after_success:
        - npm i -g semantic-release @semantic-release/exec && semantic-release
branches:
  only:
    - master
